version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - sentiment

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"

  sentiment:
    build:
      context: .
      dockerfile: Dockerfile.sentiment
    ports:
      - "5001:5001"
