import { Poppins } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import HeadLines from "@/components/HeadLines";
import I18nProvider from '@/components/I18nProvider';


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Portal Berita Terkini Winnicode Garuda Teknologi',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        <I18nProvider>
          
          {children}
        </I18nProvider>
        <Footer />
      </body>
    </html>
  );
}

